example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

katalog/urls.py
# TODO: Implement Routings Here
from django.urls import path
from katalog.views import show_katalog


urlpatterns = [
    path('', show_katalog, name='show_katalog'),
]

mywatchlist/urls.py
from django.urls import path
from mywatchlist.views import show_watchlist
from mywatchlist.views import show_byxml
from mywatchlist.views import show_byjson
from mywatchlist.views import show_byhtml

app_name = 'mywatchlist'

urlpatterns = [
    path('', show_watchlist, name='show_watchlist'),
    path('xml/', show_byxml, name='show_byxml'),
    path('json/', show_byjson, name='show_byjson'),
    path('html/', show_byhtml, name='show_byhtml'),

]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
]

# TODO: Implement Routings Here

todolist/urls.py
# Implement Routings Here
from django.urls import path
from todolist.views import add_task, show_json_by_id, show_todolist
from todolist.views import register
from todolist.views import login_user
from todolist.views import logout_user
from todolist.views import create_task
from todolist.views import status
from todolist.views import delete

app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name='show_todolist'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('create-task/', create_task, name='create_task'),
    path('change/<int:id>', status, name='status'),
    path('delete/<int:id>', delete, name='delete'),
    path('json/', show_json_by_id, name='show_json_by_id'),
    path('add/', add_task, name='add_task'),
]

example_app/models.py
from django.db import models

# Create your models here.

katalog/models.py
from django.db import models

class CatalogItem(models.Model):
    item_name = models.CharField(max_length=255)
    item_price = models.BigIntegerField()
    item_stock = models.IntegerField()
    description = models.TextField()
    rating = models.IntegerField()
    item_url = models.URLField()

mywatchlist/models.py
from django.db import models

# Create your models here.
class WatchList(models.Model):
    watched = models.TextField()
    title = models.TextField()
    rating = models.IntegerField()
    release_date = models.TextField()
    review = models.TextField()

todolist/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE) 
    date = models.TextField()
    title = models.CharField(max_length=255)
    description = models.TextField()
    finished = models.BooleanField(default=False)

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

katalog/views.py
from django.shortcuts import render
from katalog.models import CatalogItem
# TODO: Create your views here.
def show_katalog(request):
    return render(request, 'katalog.html', context)

data_katalog = CatalogItem.objects.all()
context = {
    'list_katalog': data_katalog,
    'nama': 'Refiany Shadrina',
    'npm' : 2106650185
}

mywatchlist/views.py
from django.shortcuts import render
from mywatchlist.models import WatchList
from django.http import HttpResponse
from django.core import serializers

# Create your views here.
def show_watchlist(request):
    return render(request, 'mywatchlist.html', context)

data_watchlist = WatchList.objects.all()
context = {
    'watchlist_data': data_watchlist,
    'nama': 'Refiany Shadrina',
    'npm' : 2106650185
}

def show_byhtml(request):
    return render(request, 'watchedListData.html', contextHtml)

contextHtml = {
    'watchlist_data': data_watchlist
}

def show_byxml(request):
    data = WatchList.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_byjson(request):
    data = WatchList.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

todolist/views.py
from django.shortcuts import render
from todolist.models import Task
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
import datetime
from todolist.form_todolist import TaskForm
from django.contrib.auth import logout
from django.core import serializers
from django.views.decorators.csrf import csrf_exempt
# Create your views here.

@login_required(login_url='/todolist/login/')
def show_todolist(request):
    username = None

    if request.user.is_authenticated:
        username = request.user.get_username()
    
    # data_todolist = Task.objects.filter(user = request.user)
    context = {
        # 'list_todo': data_todolist,
        'username': username,
        'user' : request.user,
        'last_login': request.COOKIES.get('last_login')
    }
    return render(request, "todolist.html", context)

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("todolist:show_todolist")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    response.delete_cookie('last_login')
    return response

@login_required(login_url='/todolist/login/')
def create_task(request):
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            title = request.POST.get('title')
            description = request.POST.get('description')
            Task.objects.create(title=title, description=description, date=datetime.datetime.now(), user=request.user)
            return redirect('todolist:show_todolist')
    
    else:
        form = TaskForm()
 
    context = {'form':form}
    return render(request, 'create-task.html', context)

@login_required(login_url='/todolist/login/')
def status(request, id):
    task = Task.objects.get(id = id)
    task.finished = not(task.finished)
    task.save()
    return redirect('todolist:show_todolist')

@login_required(login_url='/todolist/login/')
def delete(request, id):
    task = Task.objects.get(id = id)
    task.delete()
    return redirect('todolist:show_todolist')

@login_required(login_url='/todolist/login/')
def show_json_by_id(request):
    task = Task.objects.filter(user = request.user)
    return HttpResponse(serializers.serialize("json", task), content_type="application/json")

@login_required(login_url='/todolist/login/')
@csrf_exempt
def add_task(request):
     if request.method == 'POST':
        title = request.POST.get('title')
        description = request.POST.get('description')
        task = Task.objects.create(title=title, description=description, date=datetime.date.today(), finished=False, user=request.user)

        output = {
            'pk':task.pk,
            'fields':{
                'title':task.title,
                'description':task.description,
                'finished':task.finished,
                'date':task.date,
            }
        }

        return JsonResponse(output)

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

katalog/templates/katalog.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Lab 1 Assignment PBP/PBD</h1>

  <h5>Name: </h5>
  <p>{{nama}}</p>

  <h5>Student ID: </h5>
  <p>{{npm}}</p>

  <table>
    <tr>
      <th>Item Name</th>
      <th>Item Price</th>
      <th>Item Stock</th>
      <th>Rating</th>
      <th>Description</th>
      <th>Item URL</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for katalog in list_katalog %}
    <tr>
      <th>{{ katalog.item_name }}</th>
      <th>{{ katalog.item_price }}</th>
      <th>{{ katalog.item_stock }}</th>
      <th>{{ katalog.rating }}</th>
      <th>{{ katalog.description }}</th>
      <th>{{ katalog.item_url }}</th>
    </tr>
    {% endfor %}
  </table>

 {% endblock content %}

mywatchlist/templates/mywatchlist.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Assignment 3 PBP</h1>

  <h5>Name: </h5>
  <p>{{nama}}</p>

  <h5>Student ID: </h5>
  <p>{{npm}}</p>

  <table>
    <tr>
      <th>Watched</th>
      <th>Title</th>
      <th>Rating</th>
      <th>Release Date</th>
      <th>Review</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for watchlist in watchlist_data %}
    <tr>
      <th>{{ watchlist.watched }}</th>
      <th>{{ watchlist.title }}</th>
      <th>{{ watchlist.rating }}</th>
      <th>{{ watchlist.release_date }}</th>
      <th>{{ watchlist.review }}</th>
    </tr>
    {% endfor %}
  </table>

 {% endblock content %}

mywatchlist/templates/watchedListData.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Watch List</h1>

  <table>
    <tr>
      <th>Watched</th>
      <th>Title</th>
      <th>Rating</th>
      <th>Release Date</th>
      <th>Review</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for watchlist in watchlist_data %}
    <tr>
      <th>{{ watchlist.watched }}</th>
      <th>{{ watchlist.title }}</th>
      <th>{{ watchlist.rating }}</th>
      <th>{{ watchlist.release_date }}</th>
      <th>{{ watchlist.review }}</th>
    </tr>
    {% endfor %}
  </table>

 {% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  <script src="https://cdn.tailwindcss.com"></script>
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</body>

</html>

todolist/templates/create-task.html
{% extends 'base.html' %}

 {% block content %}

 <style>
    .gradient-custom {
      background-color: hsl(218, 41%, 15%);
      background-image: radial-gradient(650px circle at 0% 0%,
          hsl(218, 41%, 35%) 15%,
          hsl(218, 41%, 30%) 35%,
          hsl(218, 41%, 20%) 75%,
          hsl(218, 41%, 19%) 80%,
          transparent 100%),
        radial-gradient(1250px circle at 100% 100%,
          hsl(218, 41%, 45%) 15%,
          hsl(218, 41%, 30%) 35%,
          hsl(218, 41%, 20%) 75%,
          hsl(218, 41%, 19%) 80%,
          transparent 100%);
    }
 </style>

<section class="vh-100 gradient-custom">

  <h1 class="text-light" style="text-align: center;">Create Task</h1>

    <form method="POST">
        {% csrf_token %}
        <table class="text-light" style="margin-left: auto;margin-right: auto;margin-top: auto;margin-bottom: auto;">  
            {{ form.as_table }}  
            <tr>  
                <td></td>
                <td><input type="submit" name="submit" value="Create"/></td>  
            </tr>  
        </table> 
    </form>
</section>
{% endblock content %}

todolist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<!-- Section: Design Block -->
<section class="background-radial-gradient overflow-hidden">
    <style>
      .background-radial-gradient {
        background-color: hsl(73, 92%, 25%);
        background-image: radial-gradient(650px circle at 0% 0%,
            hsl(150, 13%, 42%) 15%,
            hsl(145, 52%, 61%) 35%,
            hsl(220, 22%, 52%) 75%,
            hsl(147, 17%, 53%) 80%,
            transparent 100%),
          radial-gradient(1250px circle at 100% 100%,
            hsl(218, 41%, 45%) 15%,
            hsl(219, 41%, 13%) 35%,
            hsl(218, 41%, 20%) 75%,
            hsl(218, 41%, 19%) 80%,
            transparent 100%);
      }

      .card {
        background-color: hsl(73, 83%, 81%);
      }
  
      .bg-glass {
        background-color: hsla(0, 0%, 100%, 0.9) !important;
        backdrop-filter: saturate(200%) blur(25px);
      }
    </style>
  
    <div class="container px-4 py-5 px-md-5 text-center text-lg-start my-5">
      <div class="row gx-lg-5 align-items-center mb-5">
        <div class="col-lg-6 mb-5 mb-lg-0" style="z-index: 10">
          <h1 class="my-5 display-5 fw-bold ls-tight" style="color: hsl(218, 81%, 95%)">
            Log In <br />
            <span style="color: hsl(44, 81%, 75%)">for your everyday to-do list!</span>
          </h1>
          <p class="mb-4 opacity-70" style="color: hsl(218, 81%, 85%)">
            Fakultas Ilmu Komputer
            Universitas Indonesia
          </p>
        </div>
  
        <div class="col-lg-6 mb-5 mb-lg-0 position-relative">
  
            <div class="card-body px-4 py-5 px-md-5">
                <div class="card text-white" style="border-radius: 1rem;">
                    <div class="card-body p-5 text-center">
                        <div class="mb-md-5 mt-md-4 pb-5">
                            <h2 class="fw-bold mb-2 text-uppercase text-dark">Login First!</h2>
                            <p class="mb-5 text-dark">Please enter your login and password</p>
                            <form method="POST" action="">
                                {% csrf_token %}
                                <table>
                                    <div class="form-outline form-white mb-4">
                                        <input type="text" id="typeUsername" name="username" placeholder="Username" class="form-control" />
                                    </div>
                                    
                                    <div class="form-outline form-white mb-4">
                                        <input type="password" name="password" placeholder="Password" id="typePasswordX" class="form-control" />
                                    </div>
                                    <div class="text-dark">
                                    {% if messages %}
                                        <ul>
                                            {% for message in messages %}
                                                <li>{{ message }}</li>
                                            {% endfor %}
                                        </ul>
                                    {% endif %} 
                                    </div>
                                    <button class="btn btn-outline-dark btn-lg px-5" type="submit" value="Login">Login</button>
                                </table>
                            </form>
                            
                        </div>
                        <p class="mb-0 text-dark">Don't have an account? <a href="{% url 'todolist:register' %}" class="text-dark-50 fw-bold">Sign Up</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
      </div>
    </div>
  </section>
  <!-- Section: Design Block -->
{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<!-- Section: Design Block -->
<section class="background-radial-gradient overflow-hidden">
    <style>
      .background-radial-gradient {
        background-color: hsl(73, 92%, 25%);
        background-image: radial-gradient(650px circle at 0% 0%,
            hsl(150, 13%, 42%) 15%,
            hsl(145, 52%, 61%) 35%,
            hsl(220, 22%, 52%) 75%,
            hsl(147, 17%, 53%) 80%,
            transparent 100%),
          radial-gradient(1250px circle at 100% 100%,
            hsl(218, 41%, 45%) 15%,
            hsl(219, 41%, 13%) 35%,
            hsl(218, 41%, 20%) 75%,
            hsl(218, 41%, 19%) 80%,
            transparent 100%);
      }
  
      .bg-glass {
        background-color: hsla(0, 0%, 100%, 0.9) !important;
        backdrop-filter: saturate(200%) blur(25px);
      }
    </style>
  
    <div class="container px-4 py-5 px-md-5 text-center text-lg-start my-5">
      <div class="row gx-lg-5 align-items-center mb-5">
        <div class="col-lg-6 mb-5 mb-lg-0" style="z-index: 10">
          <h1 class="my-5 display-5 fw-bold ls-tight" style="color: hsl(218, 81%, 95%)">
            Sign Up <br />
            <span style="color: hsl(44, 81%, 75%)">for your everyday to-do list!</span>
          </h1>
          <p class="mb-4 opacity-70" style="color: hsl(218, 81%, 85%)">
            Fakultas Ilmu Komputer
            Universitas Indonesia
          </p>
        </div>
  
        <div class="col-lg-6 mb-5 mb-lg-0 position-relative">
  
          <div class="card bg-glass">
            <div class="card-body px-4 py-5 px-md-5">
                <form method="POST" >  
                    {% csrf_token %}  
                    <table>  
                        {{ form.as_table }}  
                        <tr>  
                            <td></td>
                            <td><input type="submit" name="submit" value="SignUp"/></td>  
                        </tr>  
                    </table>  
                </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- Section: Design Block -->
{% endblock content %}

todolist/templates/todolist.html
 
{% extends 'base.html' %}
 
{% block content %}

<head>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>

  $(document).ready(function(){
      const card = (data) =>  
        `<div id="${data.pk}-card" align="center">
          <div class="card" style="width: 18rem;">
               <div class="card-body">
                 <h5 class="card-title">${data.fields.title}</h5>
                 <h6 class="card-subtitle mb-2 text-muted">${data.fields.date}</h6>
                 <p class="card-text">${data.fields.description}</p>
                 ${data.fields.finished ?`<h6 class="card-text text-success">FINISHED</h6>
                   <a href="/todolist/delete/${data.pk}"><button class="btn btn-outline-dark" >Delete</button></a>
                   <a href="/todolist/change/${data.pk}"><button class="btn btn-outline-dark">Undo</button></a>`:
                   `<h6 class="card-text text-danger">ON PROGRESS</h6>
                   <a href="/todolist/delete/${data.pk}"><button class="btn btn-outline-dark">Delete</button></a>
                   <a href="/todolist/change/${data.pk}"><button class="btn btn-outline-dark">Mark as Done</button></a>`
               }
               </div>
             </div>
           </div>`

   const addCard = (data) => {
        return $('#todo').append(card(data))
    }

    $.get('/todolist/json', function (todo) {
        todo.map((task) => {
          addCard(task)
        })
      })

    $('#addTask').click(function() {
      if ($('#title').val() && $('#description').val()) {
        $.post(
          '/todolist/add/',
          {
            title: $('#title').val(),
            description: $('#description').val(),
          },
          function(res,status) {
            if (status=='success') {
              addCard(res)
              $('#title').val('')
              $('#description').val('')
            }
          }
        )
        return false;
      }
    })
  });
</script>
</head>


<style>
 .background-radial-gradient {
       background-color: hsl(73, 88%, 76%);
       background-image: radial-gradient(650px circle at 0% 0%,
           hsl(56, 71%, 73%) 15%,
           hsl(54, 52%, 61%) 35%,
           hsl(46, 60%, 73%) 75%,
           hsl(73, 66%, 66%) 80%,
           transparent 100%),
         radial-gradient(1250px circle at 100% 100%,
           hsl(61, 61%, 60%) 15%,
           hsl(64, 39%, 72%) 35%,
           hsl(46, 55%, 60%) 75%,
           hsl(81, 100%, 75%) 80%,
           transparent 100%);
     }
 .card {
   padding-left: 20px;
   padding-right: 20px;
   box-shadow: 0 0px 20px 0 rgba(0,0,0,0.2);
   background-color: rgba(193, 230, 207, 0.699);
   transition: 0.3s;
   cursor: pointer;
   display: flex;
   width: 100%;
   margin-bottom: 10px;
   margin-top: 10px;
   margin-left: 5px;
   margin-right: 5px;
}
.card:hover{
   transform: scale(1.09);
   box-shadow: 0 10px 20px rgba(0,0,0,.12), 0 4px 8px rgba(0,0,0,.06);
 }
 body {
   background-color: hsl(73, 92%, 25%);
       background-image: radial-gradient(650px circle at 0% 0%,
           hsl(150, 13%, 42%) 15%,
           hsl(145, 52%, 61%) 35%,
           hsl(220, 22%, 52%) 75%,
           hsl(147, 17%, 53%) 80%,
           transparent 100%),
         radial-gradient(1250px circle at 100% 100%,
           hsl(218, 41%, 45%) 15%,
           hsl(219, 41%, 13%) 35%,
           hsl(218, 41%, 20%) 75%,
           hsl(218, 41%, 19%) 80%,
           transparent 100%);
 }
 </style>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
 <div class="container-fluid navbar-dark bg-dark">
     <a class="navbar-brand navbar-dark bg-dark">Hello, {{user.get_username}}!</a>
     <button class="navbar-toggler navbar-dark bg-dark" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon navbar-dark bg-dark"></span>
       </button>
       <div class="collapse navbar-collapse navbar-dark bg-dark" id="navbarSupportedContent">
           <ul class="navbar-nav">
             <li class="nav-item active">
               <a class="nav-link navbar-dark bg-dark cursor-pointer" data-bs-toggle="modal" data-bs-target="#createTaskModal">Add Task<span class="sr-only navbar-dark bg-dark"></span></a>
             </li>
             <li class="nav-item">
               <a class="nav-link navbar-dark bg-dark" href="{% url 'todolist:logout' %}">Logout</a>
             </li>
           </ul>
       </div>
 </div>
</nav>


 <div class="modal fade" id="createTaskModal" tabindex="-1" role="dialog" aria-labelledby="createTaskModalLabel" aria-hidden="true">
   <div class="modal-dialog bg-dark" role="document">
     <div class="modal-content bg-dark">
       <div class="modal-header">
         <h5 class="modal-title text-white" id="createTaskModalLabel">Add Task</h5>
       </div>
       <div class="modal-body">
        <form method="post">
         {% csrf_token %}
         
        </form>
         <label class="text-white font-bold">Title</label>
         <input id="title"  type="title" name="title" placeholder="Task Title">
         <label class="text-white font-bold">Description</label>
         <input id="description"  type="description" name="description" placeholder="Task Description">
       </div>
       <div class="modal-footer">
         <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
         <button id="addTask" type="submit" class="btn btn-primary" data-bs-dismiss="modal">Add</button>
       </div>
        
     </div>
   </div>
 </div>


 <h2 class="text-center text-light"> </h2>

 <div id="todo"></div>

      
  

{% endblock content %}